/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngudc.draw;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Duong Chinh Ngu
 */
public class DrawShapeFrame extends javax.swing.JFrame {
    Point p1 = null;
    Point p2 = null;
    int color = Color.blue.getRGB();
    String shape = "line";
    Graphics g = null;
    /**
     * Creates new form DrawShapeFrame
     */
    public DrawShapeFrame() {
        initComponents();
        setLocationRelativeTo(this);
        g = pnlScreen.getGraphics();
    }
    
    public void draw()
    {
        Color c = new Color(color);
        g.setColor(c);
        
        if( shape.equalsIgnoreCase("line"))
            g.drawLine(p1.x, p1.y, p2.x, p2.y);
        if( shape.equalsIgnoreCase("oval"))
            drawOval();
        if( shape.equalsIgnoreCase("rect"))
            drawRect();
        if( shape.equalsIgnoreCase("roundRect"))
            drawRoundRect();
    }
    
    public void drawOval()
    {
        int x = p1.x<p2.x? p1.x : p2.x ;
        int y = p1.y < p2.y ? p1.y : p2.y;
                
        int width = p1.x - p2.x;
        if( width < 0) width = -width;
        
        int height = p1.y - p2.y;
        if( height < 0) height = -height;
        
        g.drawOval(x, y, width, height);
        
        
    }
    
    public void drawRect()
    {
        int x = p1.x<p2.x? p1.x : p2.x ;
        int y = p1.y < p2.y ? p1.y : p2.y;
                
        int width = p1.x - p2.x;
        if( width < 0) width = -width;
        
        int height = p1.y - p2.y;
        if( height < 0) height = -height;
        
        g.fillRect(x, y, width, height);
        
    }
    
    public void drawRoundRect()
    {
        int x = p1.x<p2.x? p1.x : p2.x ;
        int y = p1.y < p2.y ? p1.y : p2.y;
                
        int width = p1.x - p2.x;
        if( width < 0) width = -width;
        
        int height = p1.y - p2.y;
        if( height < 0) height = -height;
        
        g.drawRect(x, y, width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlScreen = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnOval = new javax.swing.JMenuItem();
        mnRoundRect = new javax.swing.JMenuItem();
        mnRect = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnBlue = new javax.swing.JRadioButtonMenuItem();
        mnGreen = new javax.swing.JRadioButtonMenuItem();
        mnRed = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlScreenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlScreenMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlScreenLayout = new javax.swing.GroupLayout(pnlScreen);
        pnlScreen.setLayout(pnlScreenLayout);
        pnlScreenLayout.setHorizontalGroup(
            pnlScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        pnlScreenLayout.setVerticalGroup(
            pnlScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        getContentPane().add(pnlScreen);

        jMenu1.setText("Add");

        mnOval.setText("Oval");
        mnOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOvalActionPerformed(evt);
            }
        });
        jMenu1.add(mnOval);

        mnRoundRect.setText("Round Rectangle");
        mnRoundRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRoundRectActionPerformed(evt);
            }
        });
        jMenu1.add(mnRoundRect);

        mnRect.setText("Rectangle");
        mnRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRectActionPerformed(evt);
            }
        });
        jMenu1.add(mnRect);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Color");

        buttonGroup1.add(mnBlue);
        mnBlue.setSelected(true);
        mnBlue.setText("Blue");
        mnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBlueActionPerformed(evt);
            }
        });
        jMenu2.add(mnBlue);

        buttonGroup1.add(mnGreen);
        mnGreen.setText("Green");
        mnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGreenActionPerformed(evt);
            }
        });
        jMenu2.add(mnGreen);

        buttonGroup1.add(mnRed);
        mnRed.setText("Red");
        mnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRedActionPerformed(evt);
            }
        });
        jMenu2.add(mnRed);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Option");

        mnClear.setText("Clear Shape");
        mnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClearActionPerformed(evt);
            }
        });
        jMenu3.add(mnClear);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlScreenMousePressed
        // TODO add your handling code here:
        p1 = evt.getPoint();
    }//GEN-LAST:event_pnlScreenMousePressed

    private void pnlScreenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlScreenMouseReleased
        // TODO add your handling code here:
        p2 = evt.getPoint();
        draw();
    }//GEN-LAST:event_pnlScreenMouseReleased

    private void mnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBlueActionPerformed
        // TODO add your handling code here:
        color = Color.blue.getRGB();
    }//GEN-LAST:event_mnBlueActionPerformed

    private void mnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGreenActionPerformed
        // TODO add your handling code here:
        color = Color.green.getRGB();
    }//GEN-LAST:event_mnGreenActionPerformed

    private void mnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRedActionPerformed
        // TODO add your handling code here:
        color = Color.red.getRGB();
    }//GEN-LAST:event_mnRedActionPerformed

    private void mnOvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOvalActionPerformed
        // TODO add your handling code here:
        shape = "oval";
    }//GEN-LAST:event_mnOvalActionPerformed

    private void mnRoundRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRoundRectActionPerformed
        // TODO add your handling code here:
        shape = "roundRect";
    }//GEN-LAST:event_mnRoundRectActionPerformed

    private void mnRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRectActionPerformed
        // TODO add your handling code here:
        shape = "rect";
    }//GEN-LAST:event_mnRectActionPerformed

    private void mnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClearActionPerformed
        // TODO add your handling code here:
        pnlScreen.repaint();
    }//GEN-LAST:event_mnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawShapeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawShapeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawShapeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawShapeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawShapeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem mnBlue;
    private javax.swing.JMenuItem mnClear;
    private javax.swing.JRadioButtonMenuItem mnGreen;
    private javax.swing.JMenuItem mnOval;
    private javax.swing.JMenuItem mnRect;
    private javax.swing.JRadioButtonMenuItem mnRed;
    private javax.swing.JMenuItem mnRoundRect;
    private javax.swing.JPanel pnlScreen;
    // End of variables declaration//GEN-END:variables
}
